// Generated by bun-plugin-auto-imports
//
// Sequential `await import(...)` instead of static `import` / `export *`.
// Static imports are linked in parallel — Bun starts evaluating model #2's
// body before model #1 (and its `@stacksjs/validation` dep) finishes, so
// model #2 hits a TDZ on `schema`. Awaited dynamic imports are a true
// barrier: the next line doesn't run until the previous module has fully
// evaluated, including all its transitive deps.
const _Payment = (await import('../../../app/Models/Payment')).default
const _Customer = (await import('../../../app/Models/Customer')).default
const _HostProfile = (await import('../../../app/Models/HostProfile')).default
const _PaymentMethod = (await import('../../../app/Models/PaymentMethod')).default
const _Car = (await import('../../../app/Models/Car')).default
const _Location = (await import('../../../app/Models/Location')).default
const _PaymentTransaction = (await import('../../../app/Models/PaymentTransaction')).default
const _Review = (await import('../../../app/Models/Review')).default
const _Booking = (await import('../../../app/Models/Booking')).default
const _Coupon = (await import('../../../app/Models/Coupon')).default
const _TaxRate = (await import('../../../app/Models/TaxRate')).default
const _Subscription = (await import('../../../app/Models/Subscription')).default
const _User = (await import('../../../app/Models/User')).default
const _Extra = (await import('../../../app/Models/Extra')).default
const _CarPhoto = (await import('../../../app/Models/CarPhoto')).default
const _Tag = (await import('../defaults/app/Models/Tag')).default
const _PaymentProduct = (await import('../defaults/app/Models/PaymentProduct')).default
const _FailedJob = (await import('../defaults/app/Models/FailedJob')).default
const _SocialPost = (await import('../defaults/app/Models/SocialPost')).default
const _Campaign = (await import('../defaults/app/Models/Campaign')).default
// Skipped 'Request' — would shadow a built-in global. Import directly if needed.
const _Activity = (await import('../defaults/app/Models/Activity')).default
const _EmailList = (await import('../defaults/app/Models/EmailList')).default
const _Notification = (await import('../defaults/app/Models/Notification')).default
const _Job = (await import('../defaults/app/Models/Job')).default
const _Log = (await import('../defaults/app/Models/Log')).default
// Skipped 'Error' — would shadow a built-in global. Import directly if needed.
const _Comment = (await import('../defaults/app/Models/Comment')).default
const _Page = (await import('../defaults/app/Models/Content/Page')).default
const _Author = (await import('../defaults/app/Models/Content/Author')).default
const _Post = (await import('../defaults/app/Models/Content/Post')).default
const _Websocket = (await import('../defaults/app/Models/realtime/Websocket')).default

export {
  _Payment as Payment,
  _Customer as Customer,
  _HostProfile as HostProfile,
  _PaymentMethod as PaymentMethod,
  _Car as Car,
  _Location as Location,
  _PaymentTransaction as PaymentTransaction,
  _Review as Review,
  _Booking as Booking,
  _Coupon as Coupon,
  _TaxRate as TaxRate,
  _Subscription as Subscription,
  _User as User,
  _Extra as Extra,
  _CarPhoto as CarPhoto,
  _Tag as Tag,
  _PaymentProduct as PaymentProduct,
  _FailedJob as FailedJob,
  _SocialPost as SocialPost,
  _Campaign as Campaign,
  _Activity as Activity,
  _EmailList as EmailList,
  _Notification as Notification,
  _Job as Job,
  _Log as Log,
  _Comment as Comment,
  _Page as Page,
  _Author as Author,
  _Post as Post,
  _Websocket as Websocket,
}
