CREATE TABLE IF NOT EXISTS "relocations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "car_id" INTEGER,
  "host_profile_id" INTEGER,
  "pickup_address" TEXT,
  "pickup_location_id" INTEGER,
  "dropoff_address" TEXT,
  "dropoff_location_id" INTEGER,
  "earliest_pickup_date" TEXT,
  "latest_dropoff_date" TEXT,
  "estimated_distance_miles" INTEGER,
  "compensation_type" TEXT,
  "flat_fee" INTEGER,
  "per_mile_rate" REAL,
  "fuel_allowance" INTEGER,
  "max_extra_days" INTEGER,
  "min_age" INTEGER,
  "license_required" INTEGER,
  "status" TEXT,
  "notes" TEXT,
  "driver_id" INTEGER,
  "started_at" TEXT,
  "completed_at" TEXT,
  "start_odometer" INTEGER,
  "end_odometer" INTEGER,
  "actual_miles_driven" INTEGER,
  "payout_amount" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
