CREATE TABLE IF NOT EXISTS "bookings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "reference" TEXT,
  "car_id" INTEGER,
  "user_id" INTEGER,
  "status" TEXT,
  "start_date" TEXT,
  "end_date" TEXT,
  "pickup_time" TEXT,
  "return_time" TEXT,
  "pickup_location" TEXT,
  "delivery_address" TEXT,
  "protection_plan" TEXT,
  "subtotal" TEXT,
  "protection_fee" TEXT,
  "extras_fee" TEXT,
  "taxes" TEXT,
  "total" REAL,
  "platform_fee" TEXT,
  "payout_amount" TEXT,
  "driver_first_name" TEXT,
  "driver_last_name" TEXT,
  "driver_email" TEXT,
  "driver_phone" TEXT,
  "driver_dob" TEXT,
  "driver_license" TEXT,
  "driver_license_state" TEXT,
  "payment_method" TEXT,
  "payment_intent_id" INTEGER,
  "cancellation_reason" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);