CREATE TABLE IF NOT EXISTS "cars" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT,
  "make" TEXT,
  "model" TEXT,
  "year" REAL,
  "trim" TEXT,
  "daily_rate" REAL,
  "original_price" TEXT,
  "seats" TEXT,
  "doors" TEXT,
  "transmission" TEXT,
  "fuel_type" TEXT,
  "mpg" TEXT,
  "range" TEXT,
  "category" TEXT,
  "description" TEXT,
  "image" TEXT,
  "license_plate" TEXT,
  "vin" TEXT,
  "instant_book" TEXT,
  "delivery_available" TEXT,
  "status" TEXT,
  "rating" TEXT,
  "review_count" TEXT,
  "trips" TEXT,
  "badges" TEXT,
  "host_profile_id" INTEGER,
  "location_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);